// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_DATE_H_
#define FLATBUFFERS_GENERATED_DATE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 22 &&
              FLATBUFFERS_VERSION_MINOR == 11 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

struct FlatDate;
struct FlatDateBuilder;

struct FlatDate FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef FlatDateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_YEAR = 4,
    VT_MONTH = 6,
    VT_DAY = 8
  };
  int32_t year() const {
    return GetField<int32_t>(VT_YEAR, 0);
  }
  int32_t month() const {
    return GetField<int32_t>(VT_MONTH, 0);
  }
  int32_t day() const {
    return GetField<int32_t>(VT_DAY, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_YEAR, 4) &&
           VerifyField<int32_t>(verifier, VT_MONTH, 4) &&
           VerifyField<int32_t>(verifier, VT_DAY, 4) &&
           verifier.EndTable();
  }
};

struct FlatDateBuilder {
  typedef FlatDate Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_year(int32_t year) {
    fbb_.AddElement<int32_t>(FlatDate::VT_YEAR, year, 0);
  }
  void add_month(int32_t month) {
    fbb_.AddElement<int32_t>(FlatDate::VT_MONTH, month, 0);
  }
  void add_day(int32_t day) {
    fbb_.AddElement<int32_t>(FlatDate::VT_DAY, day, 0);
  }
  explicit FlatDateBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<FlatDate> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<FlatDate>(end);
    return o;
  }
};

inline flatbuffers::Offset<FlatDate> CreateFlatDate(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t year = 0,
    int32_t month = 0,
    int32_t day = 0) {
  FlatDateBuilder builder_(_fbb);
  builder_.add_day(day);
  builder_.add_month(month);
  builder_.add_year(year);
  return builder_.Finish();
}

inline const FlatDate *GetFlatDate(const void *buf) {
  return flatbuffers::GetRoot<FlatDate>(buf);
}

inline const FlatDate *GetSizePrefixedFlatDate(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<FlatDate>(buf);
}

inline bool VerifyFlatDateBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<FlatDate>(nullptr);
}

inline bool VerifySizePrefixedFlatDateBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<FlatDate>(nullptr);
}

inline void FinishFlatDateBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<FlatDate> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedFlatDateBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<FlatDate> root) {
  fbb.FinishSizePrefixed(root);
}

#endif  // FLATBUFFERS_GENERATED_DATE_H_
