#ifndef INT_ARRAY_VERIFIER_H
#define INT_ARRAY_VERIFIER_H

/* Generated by flatcc 0.6.1 FlatBuffers schema compiler for C by dvide.com */

#ifndef INT_ARRAY_READER_H
#include "int_array_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int IntArray_verify_table(flatcc_table_verifier_descriptor_t *td);

static int IntArray_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_vector_field(td, 0, 0, 4, 4, INT64_C(1073741823)) /* values */)) return ret;
    return flatcc_verify_ok;
}

static inline int IntArray_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, IntArray_identifier, &IntArray_verify_table);
}

static inline int IntArray_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, IntArray_type_identifier, &IntArray_verify_table);
}

static inline int IntArray_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &IntArray_verify_table);
}

static inline int IntArray_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &IntArray_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* INT_ARRAY_VERIFIER_H */
